name: Node.js CI

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-20.04

    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: tantor
          MONGO_INITDB_ROOT_PASSWORD: elephant

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: actions/setup-python@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.24.2
          run_install: true

      - name: Type Check
        run: yarn typecheck

      - name: Test
        run: yarn test
        env:
          MONGO_URL: mongodb://tantor:elephant@mongo:27017/tantor-test?authSource=admin
          MONGO_DB: tantor-test
