name: Node.js CI

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-22.04
    container: node:20-bullseye-slim

    services:
      mongo:
        image: mongo:6.0.11
        env:
          MONGO_INITDB_ROOT_USERNAME: tantor
          MONGO_INITDB_ROOT_PASSWORD: elephant
          MONGO_INITDB_DATABASE: tantor-test
        options: >-
          --health-cmd mongosh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.10
          run_install: true

      - name: Build
        run: pnpm run build

      - name: Type Check
        run: pnpm run typecheck

      - name: Test
        run: pnpm run test
        env:
          MONGO_URL: mongodb://tantor:elephant@mongo:27017/tantor-test?authSource=admin
          MONGO_DB: tantor-test
