name: Node.js CI

on: [push]

jobs:
  container-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [16.x]

    runs-on: ubuntu-20.04
    container: mhart/alpine-node:16

    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: tantor
          MONGO_INITDB_ROOT_PASSWORD: elephant

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-
            ${{ runner.os }}-

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm i

      - name: Type Check
        run: yarn typecheck

      - name: Test
        run: yarn test
        env:
          MONGO_URL: mongodb://tantor:elephant@mongo:27017/tantor-test?authSource=admin
          MONGO_DB: tantor-test
